import argparse
from sdc_parser import read_sdc


# -------------------------
# Analyze RTL
# -------------------------
def analyze_rtl(rtl_path):
    with open(rtl_path, "r", encoding="utf-8") as f:
        code = f.read()
    print(f"[Analyze] RTL parsed: {rtl_path}")
    return {"rtl_code": code}


# -------------------------
# Elaborate
# -------------------------
def elaborate(rtl):
    print("[Elaborate] Building design structure")
    return {
        "ports": ["tukli", "a", "b", "c", "y", "z"],
        "registers": ["q"],
        "logic": ["AND", "OR", "NOT"]
    }


# -------------------------
# Build generic logic
# -------------------------
def build_generic(design):
    print("[Generic] Creating GTECH-like logic")
    return ["AND", "OR", "NOT", "DFF"]
###
def write_gtech_netlist(generic, out_file="example_top.gtech.v"):
    """
    Educational GTECH-like dump.
    Assumes 'generic' is a list like ["AND","OR","NOT","DFF"].
    """
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// GTECH-like netlist generated by Gabor_synthesis\n")
        f.write("// Educational, non-production\n\n")

        f.write("module example_top_gtech (\n")
        f.write("    input tukli,\n")
        f.write("    input a,\n")
        f.write("    input b,\n")
        f.write("    input c,\n")
        f.write("    output y,\n")
        f.write("    output z\n")
        f.write(");\n\n")

        f.write("  wire n1, n2, q;\n\n")

        inst_id = 1
        for op in generic:
            if op == "DFF":
                f.write(f"  GTECH_DFF U{inst_id} (.CLK(tukli), .D(n2), .Q(q));\n")
            elif op == "AND":
                f.write(f"  GTECH_AND U{inst_id} (.A(a), .B(b), .Y(n1));\n")
            elif op == "OR":
                f.write(f"  GTECH_OR  U{inst_id} (.A(n1), .B(c), .Y(n2));\n")
            elif op == "NOT":
                f.write(f"  GTECH_NOT U{inst_id} (.A(q), .Y(z));\n")
            inst_id += 1

        f.write("\n  assign y = q;\n")
        f.write("endmodule\n")

    print(f"[GTECH] Wrote GTECH netlist: {out_file}")

    ###
def report_gtech_stats(generic):
        gate_count = len(generic)
        print("\n[GTECH REPORT]")
        print(f"Number of generic gates : {gate_count}")


# -------------------------
# Mapping
# -------------------------
def initial_mapping(generic, lib_files):
    print("[Mapping] Mapping to standard cells")
    return [
        ("AND2_X1", 0.20),
        ("OR2_X1",  0.20),
        ("INV_X1",  0.10),
        ("DFF_X1",  0.30)
    ]


# -------------------------
# Read SDC
# -------------------------


    print(f"[SDC] Clock period = {clock_period} ns")
    return clock_period


# -------------------------
# Timing analysis
# -------------------------
def timing_analysis(mapped_cells, clock_period):
    total_delay = sum(delay for _, delay in mapped_cells)
    slack = clock_period - total_delay

    print("\n--- Compile Timing Report ---")
    print(f"Clock period    : {clock_period:.2f} ns")
    print(f"Path delay      : {total_delay:.2f} ns")
    print(f"Setup slack     : {slack:.2f} ns")

    if slack < 0:
        print("STATUS: SETUP VIOLATION")
    else:
        print("STATUS: TIMING MET")

#.........................
#Gate_level_netlist
def write_gate_netlist(mapped_cells, out_file="example_top_gate.v"):
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Gate-level netlist generated by Gabor_synthesis\n")
        f.write("// Educational, non-production\n\n")

        f.write("module example_top_gate (\n")
        f.write("    input tukli,\n")
        f.write("    input a,\n")
        f.write("    input b,\n")
        f.write("    input c,\n")
        f.write("    output y,\n")
        f.write("    output z\n")
        f.write(");\n\n")

        f.write("  wire n1, n2, q;\n\n")

        inst_id = 1
        for cell, _ in mapped_cells:
            if cell == "DFF_X1":
                f.write(f"  DFF_X1 U{inst_id} (.CLK(tukli), .D(n2), .Q(q));\n")
            elif cell == "AND2_X1":
                f.write(f"  AND2_X1 U{inst_id} (.A(a), .B(b), .Y(n1));\n")
            elif cell == "OR2_X1":
                f.write(f"  OR2_X1  U{inst_id} (.A(n1), .B(c), .Y(n2));\n")
            elif cell == "INV_X1":
                f.write(f"  INV_X1  U{inst_id} (.A(q), .Y(z));\n")
            inst_id += 1

        f.write("\n  assign y = q;\n")
        f.write("endmodule\n")

    print(f"[NETLIST] Gate-level netlist written to {out_file}")

#####
def report_gate_level_stats(mapped_cells):
    gate_count = len(mapped_cells)
    print("\n[GATE-LEVEL REPORT]")
    print(f"Number of mapped cells  : {gate_count}")


# -------------------------
# Main
# -------------------------
def main():
    parser = argparse.ArgumentParser(description="Gabor_synthesis (single-file, educational)")
    parser.add_argument("--rtl", required=True)
    parser.add_argument("--lib", action="append", required=True)
    parser.add_argument("--sdc", required=True)

    args = parser.parse_args()

    rtl = analyze_rtl(args.rtl)
    design = elaborate(rtl)
    generic = build_generic(design)
    report_gtech_stats(generic)
    write_gtech_netlist(generic)
    mapped = initial_mapping(generic, args.lib)
    report_gate_level_stats(mapped)
    clock_period = read_sdc(args.sdc)
    timing_analysis(mapped, clock_period)
    write_gate_netlist(mapped)


if __name__ == "__main__":
    main()
